# SPDX-License-Identifier: MIT OR Apache-2.0

[default]
extend-ignore-re = [
    # Ignore hashes, signatures, addresses, and other long encoded test values.
    "[0-9A-Za-z]{32,150}+",
]

[default.extend-words]
Floresta = "Floresta"
outpoint = "outpoint"
outpoints = "outpoints"
