# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "floresta-db"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"
description = "A CAS-only concurrent mmap database for Floresta"
license = "MIT OR Apache-2.0"

[dependencies]
bitcoin = { version = "0.32.7", optional = true }
bitcoinkernel = { version = "0.3.0", optional = true }
hintsfile = { version = "0.1.1", optional = true }
memmap2 = { version = "0.9.5", optional = true }

[features]
default = []
bitcoin-load = ["dep:bitcoin", "dep:bitcoinkernel", "dep:hintsfile", "dep:memmap2"]

[[example]]
name = "bitcoin-load"
path = "examples/bitcoin_load/main.rs"
required-features = ["bitcoin-load"]

[lints.rust]
missing_docs = "deny"
unsafe_op_in_unsafe_fn = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
